In [1]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
import MySQLdb
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import requests
from bs4 import BeautifulSoup

In [3]:
df = pd.read_csv('한국소비자원 생필품 및 서비스 가격 정보_20220128.csv', encoding='cp949')

In [11]:
df.head()

             상품명         조사일  판매가격       판매업소   제조사 세일여부 원플러스원
0  머거본 꿀땅콩(135g)  2022-01-14  3600     CU(본사)   머거본    N     N
1  머거본 꿀땅콩(135g)  2022-01-14  2190    롯데슈퍼안양점   머거본    N     N
2  허니버터아몬드(210g)  2022-01-14  5990  롯데슈퍼김포전원점  길림양행    N     N
3  허니버터아몬드(210g)  2022-01-14  5990    롯데슈퍼길동점  길림양행    N     N
4  허니버터아몬드(210g)  2022-01-14  5990    롯데슈퍼구평점  길림양행    N     N

In [4]:
df[df['상품명'] == '허니버터아몬드(210g)'].groupby('판매가격').min()

                상품명         조사일       판매업소   제조사 세일여부 원플러스원
판매가격
3990  허니버터아몬드(210g)  2022-01-14   롯데슈퍼남가좌점  길림양행    N     N
4950  허니버터아몬드(210g)  2022-01-14  롯데슈퍼상계7동점  길림양행    N     N
4990  허니버터아몬드(210g)  2022-01-14    롯데슈퍼상남점  길림양행    N     N
5990  허니버터아몬드(210g)  2022-01-14   롯데슈퍼G유진점  길림양행    N     N
6990  허니버터아몬드(210g)  2022-01-14   롯데슈퍼G강서점  길림양행    N     N
7480  허니버터아몬드(210g)  2022-01-14    이마트가든5점  길림양행  NaN   NaN
8900  허니버터아몬드(210g)  2022-01-28  신세계백화점강남점  길림양행  NaN   NaN

                                                 조사일                 \
상품명            3M 후레쉬 슬라이드 지퍼백 중형(21cm x 16cm x 6cm) 3분 쇠고기짜장(200g)
판매업소
(주)농협대전유통                                 2022-01-28     2022-01-28
(주)농협유통 양재점                               2022-01-28     2022-01-28
(주)농협유통 창동점                               2022-01-28     2022-01-28
(주)농협하나로유통 고양점                            2022-01-28     2022-01-28
(주)농협하나로유통 광주점                            2022-01-28     2022-01-28
...                                              ...            ...
이마트화성봉담점                                  2022-01-28     2022-01-28
이마트화정점                                    2022-01-28     2022-01-28
이마트흥덕점                                    2022-01-14     2022-01-28
현대백화점목동점                                         NaN            NaN
현대백화점천호점                                         NaN     2022-01-14

                                                                   \
상품명            3분 쇠고기카레(200g) CJ 더안심 건강란(대란 15개) CJ 비비고 왕교자(910g)
판매업소
(주)농협대전유통          2022-01-28                NaN              NaN
(주)농협유통 양재점        2022-01-28                NaN              NaN
(주)농협유통 창동점        2022-01-28                NaN              NaN
(주)농협하나로유통 고양점     2022-01-28                NaN              NaN
(주)농협하나로유통 광주점     2022-01-28                NaN              NaN
...                       ...                ...              ...
이마트화성봉담점           2022-01-28                NaN              NaN
이마트화정점             2022-01-28                NaN              NaN
이마트흥덕점             2022-01-28                NaN              NaN
현대백화점목동점           2022-01-28                NaN              NaN
현대백화점천호점                  NaN                NaN              NaN

                                                                         \
상품명            CJ 알짜란(대란 15개) CJ 행복한콩 국산콩 콩나물(280g) JB 뉴 베드타임 로션(500ml)
판매업소
(주)농협대전유통                 NaN                   NaN          2022-01-28
(주)농협유통 양재점               NaN                   NaN          2022-01-28
(주)농협유통 창동점               NaN                   NaN          2022-01-28
(주)농협하나로유통 고양점            NaN                   NaN          2022-01-28
(주)농협하나로유통 광주점            NaN                   NaN          2022-01-28
...                       ...                   ...                 ...
이마트화성봉담점                  NaN                   NaN          2022-01-14
이마트화정점                    NaN                   NaN          2022-01-28
이마트흥덕점                    NaN                   NaN          2022-01-28
현대백화점목동점                  NaN                   NaN                 NaN
현대백화점천호점                  NaN                   NaN                 NaN

                                                  ...     판매가격          \
상품명            PACE6 스타일 면도날(4개) 가그린 오리지널(750ml)  ... 햇반(210g) 햇반(3개입)
판매업소                                              ...
(주)농협대전유통             2022-01-28      2022-01-28  ...      NaN     NaN
(주)농협유통 양재점           2022-01-28      2022-01-28  ...   1700.0     NaN
(주)농협유통 창동점           2022-01-28      2022-01-28  ...      NaN     NaN
(주)농협하나로유통 고양점        2022-01-28      2022-01-28  ...      NaN     NaN
(주)농협하나로유통 광주점        2022-01-28      2022-01-28  ...   1700.0     NaN
...                          ...             ...  ...      ...     ...
이마트화성봉담점                     NaN      2022-01-28  ...   1700.0  3880.0
이마트화정점                       NaN      2022-01-28  ...   1700.0  3880.0
이마트흥덕점                       NaN      2022-01-28  ...   1700.0  3880.0
현대백화점목동점                     NaN             NaN  ...      NaN     NaN
현대백화점천호점                     NaN             NaN  ...   2110.0  5860.0

                                                                      \
상품명            햇반(6개입) 행복한콩 부침두부(300g) 행복한콩 찌개두부(300g) 허니버터아몬드(210g)
판매업소
(주)농협대전유통       7980.0             NaN             NaN           NaN
(주)농협유통 양재점     7480.0             NaN             NaN           NaN
(주)농협유통 창동점     7480.0             NaN             NaN           NaN
(주)농협하나로유통 고양점  7480.0             NaN             NaN           NaN
(주)농협하나로유통 광주점  7480.0             NaN             NaN           NaN
...                ...             ...             ...           ...
이마트화성봉담점           NaN             NaN          1100.0        7480.0
이마트화정점             NaN             NaN          1100.0        7480.0
이마트흥덕점             NaN             NaN          1100.0        7480.0
현대백화점목동점        8640.0             NaN             NaN           NaN
현대백화점천호점           NaN             NaN             NaN           NaN

                                                                            \
상품명            홈스타 락스와세제 후로랄파인(750ml) 홈스타 욕실용 세정제(900ml) 홈키파 수성 에어졸(500ml)
판매업소
(주)농협대전유통                      3300.0                NaN            5500.0
(주)농협유통 양재점                    4500.0                NaN            5500.0
(주)농협유통 창동점                    4500.0                NaN            4560.0
(주)농협하나로유통 고양점                 4500.0                NaN            5500.0
(주)농협하나로유통 광주점                 4500.0                NaN               NaN
...                               ...                ...               ...
이마트화성봉담점                       4500.0             7500.0            5500.0
이마트화정점                         4500.0             7500.0            5500.0
이마트흥덕점                         4500.0             7500.0            5500.0
현대백화점목동점                       3500.0                NaN               NaN
현대백화점천호점                          NaN                NaN               NaN


상품명            화이트 시크릿홀 날개 중형(36개입)
판매업소
(주)농협대전유통                       NaN
(주)농협유통 양재점                  9900.0
(주)농협유통 창동점                  9900.0
(주)농협하나로유통 고양점                  NaN
(주)농협하나로유통 광주점                  NaN
...                             ...
이마트화성봉담점                        NaN
이마트화정점                          NaN
이마트흥덕점                       9900.0
현대백화점목동점                        NaN
현대백화점천호점                        NaN

[546 rows x 630 columns]